### ISSUE TITLE
Auto update index.ts error https://prnt.sc/v8q0ay

### ISSUE THREAD

**Issue by vkurlov** [estruyf/vscode-typescript-exportallmodules#4]
When i try to add new file i get this error:
https://prnt.sc/v8q0ay

**Comment by estruyf** [comment]
Do you have more details on this @vkurlov? How are you using it?

**Comment by tag9724** [comment]
> Do you have more details on this @vkurlov? How are you using it?

I have the exact same error, when checking VSCode logs I have :
```command
[renderer1] [error] [Extension Host] ENOENT: no such file or directory, scandir '\projects\my-project\modules'
```

The absolute path is not resolved correctly in this case it should be :
```command
'D:\projects\my-project\modules'
```

The problem occur only when my workspace is not on my C drive so it's a problem related to windows when using other drive than the main one.

Hope it helped and thanks for making this extension.

**Comment by tag9724** [comment]
A little update, 
after investigation it seem that the problem is related to `vscodeUri.parse()` that return bad file url, for example :

```js
const folderUri = vscode.Uri.parse("d:\my-project\bad # Name")
folderUri.fsPath // return "\my-project\bad "
```


It explain why right clicking on a folder and clicking "Typescript: Export all modules" work but not the other two, the first one don't use `vscodeUri.parse(absFolder)` but  `vscodeUri.file(absFolder)`.

When we try with this one we have correct results :

```js
const folderUri = vscode.Uri.file("d:\my-project\bad # Name")
folderUri.fsPath // return "d:\my-project\bad # Name"
```


The solution is to replace every `vscodeUri.parse` by `vscodeUri.file` in the project, tested it and it work fine.

**Comment by tag9724** [comment]
Oh you've juste updated the repository, that was quick thanks.

There is just a typo left to fix in **ExportProvider.ts** line 91
```js
let fileUri = vscode.Uri.file(`file://${filePath}`);
```

Make it impossible to open any of the index.ts files from the extension menu, the `file://` part need to be removed 

```js
let fileUri = vscode.Uri.file(`${filePath}`);
```

Sorry I was not clear enough when I said to be careful with this part of the code.

**Comment by estruyf** [comment]
Updated and new release is publishing.

**Comment by tag9724** [comment]
Thank you very much, I've just updated and I can confirm everything work fine on my side now, thanks again for your time.
